### ISSUE TITLE
syntax error in _respond-to.scss

### ISSUE THREAD

**Issue by pi0** [mediamonks/seng-scss#3]
Hi there!

https://github.com/mediamonks/seng-scss/blob/master/utils/mixin/_respond-to.scss#L15

I think last closing `}` is extra

![image](https://user-images.githubusercontent.com/5158436/69676627-6b0cc700-10a1-11ea-9d5d-1ae5af06b875.png)

Also, i got complains about `@error` mixin not defined.

**Comment by ThaNarie** [comment]
The extra bracket should be removed in 1.2.2, hopefully that unbreaks your current use.
@pigeonfresh Can you have a look why `@error` doesn't seem to work?

@pi0 Could you share the exact "complains" you are getting? thanks!

**Comment by pi0** [comment]
Thanks for the quick response and fix @ThaNarie :)

Actually now I'm getting something new:

```
SassError: MediaQuery small does not exist
        on line 12 of ../../node_modules/seng-scss/utils/mixin/_respond-to.scss, in mixin `respond-to`
        from line 71 of [hidden]/default.scss
>>              @error "MediaQuery #{$name} does not exist";
```

It works fine on `1.1.1`

**Comment by pigeonfresh** [comment]
@pi0 Looking at the error it seems that your MediaQuery small does not exist. So in a way the error message works :)

Does small exist?

**Comment by pi0** [comment]
Hey. Sorry for late reponse. I just looked at a repo that had this bug so i reported and now i'm just sure it was working with 1.1.1. So more guess is a breaking-change / regression happned. I'm closing issue as don't have any repro in hand.
